In-Memory SQLite Databases using Python

In [1]:
import sqlite3
import pandas as pd

# Create an in-memory SQLite database
connection = sqlite3.connect(':memory:')

# Create a cursor object to execute SQL commands
cursor = connection.cursor()

In [2]:
# Create the Students table
create_table_query = '''
CREATE TABLE Students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    age INTEGER,
    statistics_marks INTEGER,
    python_marks INTEGER,
    ml_marks INTEGER,
    dl_marks INTEGER
);
'''

cursor.execute(create_table_query)
print("Students table created.")

Students table created.

In [3]:
# Insert data into the Students table
insert_data_query = '''
INSERT INTO Students (name, age, statistics_marks, python_marks, ml_marks, dl_marks)
VALUES
('Aarav Patel', 20, 85, 90, 88, 92),
('Sophia Smith', 21, 75, 78, 82, 85),
('Liam Johnson', 22, 88, 91, 84, 89),
('Saanvi Gupta', 19, 92, 89, 95, 91),
('Olivia Brown', 23, 80, 87, 85, 90);
'''

cursor.execute(insert_data_query)
connection.commit()  # Commit the transaction

print("Data inserted into the Students table.")

Data inserted into the Students table.

In [5]:
#query for fetching data from sql

query = "Select * from Students"

df = pd.read_sql_query(query, connection)
df

   id          name  age  statistics_marks  python_marks  ml_marks  dl_marks
0   1   Aarav Patel   20                85            90        88        92
1   2  Sophia Smith   21                75            78        82        85
2   3  Liam Johnson   22                88            91        84        89
3   4  Saanvi Gupta   19                92            89        95        91
4   5  Olivia Brown   23                80            87        85        90

In [6]:
# Update a record (change 'Sophia Smith' marks in Python to 95)
update_query = "UPDATE Students SET python_marks = 95 WHERE name = 'Sophia Smith';"
cursor.execute(update_query)
connection.commit()

print("Updated Sophia Smith's Python marks.")

Updated Sophia Smith's Python marks.

In [7]:
# Verify the update
updated_df = pd.read_sql(query, connection)

print("Updated data from the Students table:")
updated_df

Updated data from the Students table:

   id          name  age  statistics_marks  python_marks  ml_marks  dl_marks
0   1   Aarav Patel   20                85            90        88        92
1   2  Sophia Smith   21                75            95        82        85
2   3  Liam Johnson   22                88            91        84        89
3   4  Saanvi Gupta   19                92            89        95        91
4   5  Olivia Brown   23                80            87        85        90

In [8]:
#closing connections

cursor.close()
connection.close()