# Task 1 - Combining the Dataset

In [1]:
#importing the libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
#changing the work directory
os.chdir('/content/')#changing the work directory

## Analysing POS Data

In [5]:
#reading the Pos_Data and using parse_dates to interpret Date column as dates
pos = pd.read_excel("POS_Data.xlsx", parse_dates=['Date'])
pos.head()

,SKU_ID,Date,Page_traffic,Revenue($),Unit_price,Units_sold,Manufacturer,Sector,Category,Segment,Brand,Product
0,SKU1009,2021-01-02,0.0,0,NaN,0,Synergix solutions,Personal Care,Beauty Products,Makeup,RadiantGlow,product_description_SKU1009
1,SKU1009,2021-01-09,0.0,0,NaN,0,Synergix solutions,Personal Care,Beauty Products,Makeup,RadiantGlow,product_description_SKU1009
2,SKU1009,2021-01-16,0.0,0,NaN,0,Synergix solutions,Personal Care,Beauty Products,Makeup,RadiantGlow,product_description_SKU1009
3,SKU1009,2021-01-23,0.0,0,NaN,0,Synergix solutions,Personal Care,Beauty Products,Makeup,RadiantGlow,product_description_SKU1009
4,SKU1009,2021-01-30,0.0,0,NaN,0,Synergix solutions,Personal Care,Beauty Products,Makeup,RadiantGlow,product_description_SKU1009

In [6]:
#check datatypes of pos columns
pos.dtypes

SKU_ID                  object
Date            datetime64[ns]
Page_traffic           float64
Revenue($)               int64
Unit_price             float64
Units_sold               int64
Manufacturer            object
Sector                  object
Category                object
Segment                 object
Brand                   object
Product                 object
dtype: object

In [7]:
#get a summary of numerical features of the dataset
pos.describe()

,Date,Page_traffic,Revenue($),Unit_price,Units_sold
count,31185,31185.000000,31185.000000,19635.000000,31185.000000
mean,2021-12-31 23:59:59.999999744,2053.829695,14386.877505,22.038169,702.274363
min,2021-01-02 00:00:00,0.000000,0.000000,0.103030,0.000000
25%,2021-07-03 00:00:00,0.000000,0.000000,16.311504,0.000000
50%,2022-01-01 00:00:00,1963.000000,14952.000000,20.746141,765.000000
75%,2022-07-02 00:00:00,3647.000000,25670.000000,25.423036,1224.000000
max,2022-12-31 00:00:00,10696.000000,48572.000000,94.133971,3386.000000
std,NaN,1979.574340,13427.614446,9.849729,647.676402

In [8]:
#get a summary of categorical features of the pos dataframe by adding a parameter "include = 'O'", where O stands for 'object'
pos.describe(include = 'O')

,SKU_ID,Manufacturer,Sector,Category,Segment,Brand,Product
count,31185,31185,31185,31185,31185,31185,31185
unique,297,1,1,1,3,1,297
top,SKU998,Synergix solutions,Personal Care,Beauty Products,Makeup,RadiantGlow,product_description_SKU998
freq,105,31185,31185,31185,17220,31185,105

In [9]:
pos = pos.drop(["Manufacturer","Sector","Category","Brand"],axis=1)

In [10]:
pos.head()

,SKU_ID,Date,Page_traffic,Revenue($),Unit_price,Units_sold,Segment,Product
0,SKU1009,2021-01-02,0.0,0,NaN,0,Makeup,product_description_SKU1009
1,SKU1009,2021-01-09,0.0,0,NaN,0,Makeup,product_description_SKU1009
2,SKU1009,2021-01-16,0.0,0,NaN,0,Makeup,product_description_SKU1009
3,SKU1009,2021-01-23,0.0,0,NaN,0,Makeup,product_description_SKU1009
4,SKU1009,2021-01-30,0.0,0,NaN,0,Makeup,product_description_SKU1009

In [11]:
pos.describe()

,Date,Page_traffic,Revenue($),Unit_price,Units_sold
count,31185,31185.000000,31185.000000,19635.000000,31185.000000
mean,2021-12-31 23:59:59.999999744,2053.829695,14386.877505,22.038169,702.274363
min,2021-01-02 00:00:00,0.000000,0.000000,0.103030,0.000000
25%,2021-07-03 00:00:00,0.000000,0.000000,16.311504,0.000000
50%,2022-01-01 00:00:00,1963.000000,14952.000000,20.746141,765.000000
75%,2022-07-02 00:00:00,3647.000000,25670.000000,25.423036,1224.000000
max,2022-12-31 00:00:00,10696.000000,48572.000000,94.133971,3386.000000
std,NaN,1979.574340,13427.614446,9.849729,647.676402

In [12]:
pos.head(25)

,SKU_ID,Date,Page_traffic,Revenue($),Unit_price,Units_sold,Segment,Product
0,SKU1009,2021-01-02,0.0,0,NaN,0,Makeup,product_description_SKU1009
1,SKU1009,2021-01-09,0.0,0,NaN,0,Makeup,product_description_SKU1009
2,SKU1009,2021-01-16,0.0,0,NaN,0,Makeup,product_description_SKU1009
3,SKU1009,2021-01-23,0.0,0,NaN,0,Makeup,product_description_SKU1009
4,SKU1009,2021-01-30,0.0,0,NaN,0,Makeup,product_description_SKU1009
5,SKU1009,2021-02-06,0.0,0,NaN,0,Makeup,product_description_SKU1009
6,SKU1009,2021-02-13,0.0,0,NaN,0,Makeup,product_description_SKU1009
7,SKU1009,2021-02-20,0.0,0,NaN,0,Makeup,product_description_SKU1009
8,SKU1009,2021-02-27,0.0,0,NaN,0,Makeup,product_description_SKU1009
9,SKU1009,2021-03-06,0.0,0,NaN,0,Makeup,product_description_SKU1009
10,SKU1009,2021-03-13,0.0,0,NaN,0,Makeup,product_description_SKU1009
11,SKU1009,2021-03-20,0.0,0,NaN,0,Makeup,product_description_SKU1009
12,SKU1009,2021-03-27,0.0,0,NaN,0,Makeup,product_description_SKU1009
13,SKU1009,2021-04-03,0.0,0,NaN,0,Makeup,product_description_SKU1009
14,SKU1009,2021-04-10,0.0,0,NaN,0,Makeup,product_description_SKU1009
15,SKU1009,2021-04-17,0.0,0,NaN,0,Makeup,product_description_SKU1009
16,SKU1009,2021-04-24,0.0,0,NaN,0,Makeup,product_description_SKU1009
17,SKU1009,2021-05-01,0.0,0,NaN,0,Makeup,product_description_SKU1009
18,SKU1009,2021-05-08,0.0,0,NaN,0,Makeup,product_description_SKU1009
19,SKU1009,2021-05-15,0.0,0,NaN,0,Makeup,product_description_SKU1009
20,SKU1009,2021-05-22,0.0,0,NaN,0,Makeup,product_description_SKU1009
21,SKU1009,2021-05-29,0.0,0,NaN,0,Makeup,product_description_SKU1009
22,SKU1009,2021-06-05,0.0,0,NaN,0,Makeup,product_description_SKU1009
23,SKU1009,2021-06-12,0.0,0,NaN,0,Makeup,product_description_SKU1009
24,SKU1009,2021-06-19,0.0,0,NaN,0,Makeup,product_description_SKU1009

In [14]:
pos["weekday"] = pos["Date"].dt.dayofweek
pos["weekday"].value_counts()

weekday
5    31185
Name: count, dtype: int64

In [16]:
import datetime, calendar

In [17]:
print(calendar.MONDAY,calendar.TUESDAY,calendar.WEDNESDAY,calendar.THURSDAY,calendar.FRIDAY,calendar.SATURDAY,calendar.SUNDAY)

0 1 2 3 4 5 6

#Final observations from pos dataframe

1. All data is aggregated at a weekly level.
2. All the dates belong to Saturdays.
3. There are more than 10K missing values in Unit_price which we will treat after combining the tables.
4. In the POS dataframe we only have one product-related information, that is: Segment. Rest of the product-related data maybe in the Product_Attribute_Data.